name: Shared Action

on:
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          ls
          echo "This is a multiline"
